cart/urls.py
from django.conf.urls import url,include
from . import views

app_name= 'cart'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='details'),

    url(r'product/(?P<prod_id>[0-9]+)/add/$', views.cart, name='cart_update'),

    url(r'product/(?P<pk>[0-9]+)/delete/$', views.CartDelete.as_view(), name='cart_delete'),
]

pythonpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
'''from django.conf.urls import include'''
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('shop.urls')),
    url(r'^cart/', include('cart.urls')),
]


#Add URL maps to redirect the base URL to our application
'''from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/cartflip/',)),
]'''

# Use static() to add url mapping to serve static files during development (only)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
app_name='shop'
urlpatterns = [
	#/
	url(r'^$', views.IndexView.as_view(), name='index'),
	#/any_id/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

cart/models.py
from django.db import models
from shop.models import Product

class Cart(models.Model):
    pr_id=models.IntegerField(primary_key=True)
    pr_logo= models.CharField(max_length=400)
    pr_title= models.CharField(max_length=200)
    pr_price= models.IntegerField()
    pr_offer= models.CharField(max_length=30)

    def __str__(self):
        return '{0} : {1}'.format(self.pr_id,self.pr_title)

shop/models.py
from django.db import models

class Product(models.Model):
    pr_id=models.IntegerField(primary_key=True)
    pr_logo=models.CharField(max_length= 400)
    pr_title= models.CharField(max_length= 200)
    pr_price= models.IntegerField()
    pr_offer= models.CharField(max_length=30)

    def __str__(self):
        return '{0} : {1}'.format(self.pr_id,self.pr_title)

cart/views.py
from django.shortcuts import render,get_object_or_404
from django.views import generic
from shop.models import Product
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse,reverse_lazy
from cart.models import Cart

class IndexView(generic.ListView):
    template_name = 'cart/cart_page.html'
    context_object_name='cart_product'

    def get_queryset(self):
        return Cart.objects.all()


class CartDelete(DeleteView):
    model = Cart
    success_url = reverse_lazy('cart:details')

def cart(request,prod_id):
    product_items = get_object_or_404(Product,pk=prod_id)
    cart_items = Cart(pr_id=product_items.pr_id, pr_logo=product_items.pr_logo,
        pr_title=product_items.pr_title, pr_price=product_items.pr_price, pr_offer=product_items.pr_offer)
    cart_items.save()
    cart_product = Cart.objects.all()
    return render(request, 'cart/cart_page.html', {'cart_product':cart_product})

shop/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from shop.models import Product

class IndexView(generic.ListView):
	template_name = 'shop/index.html'
	context_object_name = 'all_products'

	def get_queryset(self):
		return Product.objects.all()

class DetailView(generic.DetailView):
	model = Product
	template_name = 'shop/detail.html'

cart/templates/cart/cart_page.html
{% include "shop/base.html" %}
{% load staticfiles %}
  <link rel="stylesheet" href="{% static 'cart/css/cart_page.css' %}" type="text/css">
  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}
  <div class="cart-container">
    <div class="my-cart">
      <h1>MY CART</h1>
    </div>
    <div class="product">
      {% for items in cart_product %}
        <div class="epd">

          <div class="img-div">
            <img src="{{ items.pr_logo }}" alt="{{ items.pr_title }}">
          </div>

          <div class="content">
            <div class="title-div">
              <p>{{ items.pr_title }}</p>
            </div>
            <div class="offer">
              <p>Rs. {{ items.pr_price }}</p>
              <p class="offer-view">{{ items.pr_offer }}</p>
            </div>
            <form action="{% url 'cart:cart_delete' items.pr_id %}" method="post">
              {% csrf_token %}
              <input type="submit" value="REMOVE">
            </form>
          </div>

          <div class="clearfix"></div>
        </div>
      {% endfor %}
    </div>
    <div class="button-div">
      <div class="cs-btn">
        <a href="{% url 'shop:index' %}">Continue Shopping</a>
      </div>
      <div class="po-btn">
        <a href="#">Place Order</a>
      </div>
    </div>
  </div>

shop/templates/shop/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>CartFlip</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'shop/css/base.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js"
    integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js"
    integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="main-page">
      <header>
        <div class="title">
          <h1>CartFlip</h1>
        </div>

        <div class="cart">
          <a href="{% url 'cart:details' %}">
            <i class="fas fa-cart-plus"></i>
            <a href="{% url 'cart:details' %}">Cart</a>
          </a>
        </div>
      </header>
    </div>
  </body>
</html>

shop/templates/shop/detail.html
{% include "shop/base.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'shop/css/detail_page.css' %}">
<div class="main-div">
  <div class="img-div">
    <img src="{{ product.pr_logo }}" alt="{{ product.pr_title }}">
    <form action="{% url 'cart:cart_update' product.pr_id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="ADD TO CART">
      <input type="submit" name="" value="BUY NOW">
    </form>
  </div>

  <div class="title-div">
    <h4>{{ product.pr_title }}</h4>
    <div class="offer">
      <p class="offer-view">{{ product.pr_offer }}</p>
      <p>Rs. {{ product.pr_price }}</p>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

shop/templates/shop/index.html
{% include "shop/base.html" %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'shop/css/index_page.css' %}">
<div class="main-div">
  {% for product in all_products %}
  <div class="section">
    <a href="{% url 'shop:detail' product.pr_id %}">
      <div class="img-div">
        <img src="{{ product.pr_logo }}" alt="{{ product.pr_title }}">
      </div>
      <div class="title-div">
        <h4>{{ product.pr_title }}</h4>
      </div>
      <div class="offer">
        <p>Rs. {{ product.pr_price }}</p>
        <p class="offer-view">{{ product.pr_offer }}</p>
      </div>
    </a>
  </div>
  {% endfor %}
</div>